In [1]:
a = 5
b = 6
c = a + b
print(f"La suma de {a} y {b} es {c}.") 

La suma de 5 y 6 es 11.


In [ ]:
# mostrar 10 elementos
for i in range(10):
    print(i)
    print(i+1)
print("Fin del bucle")

print("Salto de dos en dos")
for i in range(5, 10, 2):
    print(i)

print("Salto de dos en dos al revez")
for i in range(10, 5, -2):
    print(i)

0
1
1
2
2
3
3
4
4
5
5
6
6
7
7
8
8
9
9
10
Fin del bucle
5
7
9
10
8
6


In [9]:
print("Recorriendo una lista")
lista1 = [8,2,9,7,5,3,6,4,1,0]
for i in lista1:
    print(i, end =" ")


print("\nRecorriendo una cadena de texto")
lista2 = "Fabricio"
for i in lista2:
    print(i, end = ", " )

Recorriendo una lista
8 2 9 7 5 3 6 4 1 0 
Recorriendo una cadena de texto
F, a, b, r, i, c, i, o, 

In [10]:
def suma(a, b):
    return a + b

def resta(a, b):
    return a - b

# F(g(x))
def operacion(funcion, a, b):
    return funcion(a, b)

a = 5
b = 6

print(f"La suma de {a} y {b} es: {suma(a,b)}")
print(f"La resta de {a} y {b} es: {resta(a,b)}")
print(f"La suma de {a} y {b} es: {operacion(suma, a, b)}")
print(f"La resta de {a} y {b} es: {operacion(resta, a, b)}")

La suma de 5 y 6 es: 11
La resta de 5 y 6 es: -1
La suma de 5 y 6 es: 11
La resta de 5 y 6 es: -1


In [12]:
lista = [i for i in range(10)]
print(f"Lista: {lista}")

listaSum = [4 for i in range(10)]
print(f"Lista de 4: {listaSum}")
print(sum(listaSum))

def multiplicacion(a,b):
    return sum([a for i in range(b)])

print(multiplicacion(3,4))

Lista: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Lista de 4: [4, 4, 4, 4, 4, 4, 4, 4, 4, 4]
40
12


In [15]:
import numpy as np
# vector
litsaNorma = [5,6,8,9,10,11,12,13,14,15]
vector = np.array(litsaNorma)
print(f"Lista de numeros: {litsaNorma}")
print(f"Vector: \n{vector}")

# matriz
matrizNormal = [[1,2,3,4],[4,5,6,7],[7,8,9,11]]
matriz = np.array(matrizNormal)
print(f"Matriz normal: {matrizNormal}")
print(f"Matriz: \n{matriz}")

Lista de numeros: [5, 6, 8, 9, 10, 11, 12, 13, 14, 15]
Vector: 
[ 5  6  8  9 10 11 12 13 14 15]
Matriz normal: [[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 11]]
Matriz: 
[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 11]]


In [ ]:
# mediana
print(np.mean(vector))
print(np.mean(matriz))

#media
print(np.median(vector))
print(np.median(matriz))

# media por columas axis 0
# media por filas axis 1
print(matriz)
print(np.mean(matriz, axis=0))
print(np.mean(matriz, axis=1))

#desviacion estandar
print(np.std(matriz))

# comportamiento normal de 

10.3
5.583333333333333
10.5
5.5
[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 11]]
[4.         5.         6.         7.33333333]
[2.5  5.5  8.75]
2.8418988174966557
